
# Linear Algebra for Statistics, Data Science, and Machine Learning

This notebook covers the core linear algebra operations used in industry-level ML systems and statistical modeling.

Topics included:

1. Vectors and norms  
2. Matrix operations  
3. Rank and linear independence  
4. Eigenvalues and eigenvectors  
5. Positive definite matrices and Cholesky decomposition  
6. Singular Value Decomposition (SVD)  
7. Solving linear systems (stable vs unstable)  
8. Projection matrices and least squares  
9. Covariance matrices  
10. PCA from scratch  

All examples use **NumPy**, the industry standard numerical backend.


In [1]:

import numpy as np

np.set_printoptions(precision=3, suppress=True)


## 1. Vectors and Norms
The L2 norm is often used to measure magnitude.

In [2]:

x = np.array([3, 4])

l2_norm = np.linalg.norm(x)
l1_norm = np.linalg.norm(x, ord=1)

print("Vector:", x)
print("L2 norm:", l2_norm)
print("L1 norm:", l1_norm)


Vector: [3 4]
L2 norm: 5.0
L1 norm: 7.0


## 2. Matrix Multiplication
Core operation behind neural networks and regressions.

In [3]:

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = A @ B
print(C)


[[19 22]
 [43 50]]


## 3. Rank and Linear Independence

In [4]:

M = np.array([[1, 2],
              [2, 4]])  # second row is multiple of first

rank = np.linalg.matrix_rank(M)
print("Rank:", rank)


Rank: 1


## 4. Eigenvalues and Eigenvectors
Critical for covariance analysis, PCA, and stability.

In [5]:

Sigma = np.array([[2, 1],
                  [1, 2]])

eigvals, eigvecs = np.linalg.eig(Sigma)

print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.707 -0.707]
 [ 0.707  0.707]]


## 5. Positive Definite Matrices and Cholesky
Used heavily in Gaussian processes and Kalman filters.

In [6]:

L = np.linalg.cholesky(Sigma)

print("Cholesky factor L:\n", L)
print("Reconstructed matrix:\n", L @ L.T)


Cholesky factor L:
 [[1.414 0.   ]
 [0.707 1.225]]
Reconstructed matrix:
 [[2. 1.]
 [1. 2.]]


## 6. Singular Value Decomposition (SVD)
Foundation of PCA and low-rank models.

In [7]:

X = np.random.randn(5, 3)

U, S, VT = np.linalg.svd(X, full_matrices=False)

print("Singular values:", S)


Singular values: [3.704 2.169 1.368]


## 7. Solving Linear Systems
Avoid explicit matrix inversion.

In [8]:

b = np.array([1, 0])

solution = np.linalg.solve(A, b)
print("Solution:", solution)

# BAD practice:
inverse_solution = np.linalg.inv(A) @ b
print("Using inverse:", inverse_solution)


Solution: [-2.   1.5]
Using inverse: [-2.   1.5]


## 8. Least Squares and Projections
Used in linear regression.

In [9]:

X = np.random.randn(100, 3)
beta_true = np.array([1.5, -2.0, 0.5])
y = X @ beta_true + 0.1 * np.random.randn(100)

beta_hat, *_ = np.linalg.lstsq(X, y, rcond=None)

print("Estimated coefficients:", beta_hat)


Estimated coefficients: [ 1.497 -1.984  0.514]


## 9. Covariance Matrix

In [10]:

data = np.random.randn(200, 4)
cov = np.cov(data, rowvar=False)

print("Covariance matrix:\n", cov)


Covariance matrix:
 [[ 0.951 -0.015 -0.013 -0.142]
 [-0.015  1.074  0.096  0.021]
 [-0.013  0.096  0.91  -0.094]
 [-0.142  0.021 -0.094  0.957]]


## 10. PCA From Scratch

In [11]:

# Center data
X = data - data.mean(axis=0)

cov = np.cov(X, rowvar=False)
eigvals, eigvecs = np.linalg.eigh(cov)

# sort descending
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

# project
X_reduced = X @ eigvecs[:, :2]

print("Top eigenvalues:", eigvals[:2])
print("Reduced shape:", X_reduced.shape)


Top eigenvalues: [1.122 1.112]
Reduced shape: (200, 2)
